global using PhoneDirectoryLibrary.Models;
global using PhoneDirectoryLibrary.DataAccess;
global using PhoneDirectoryLibrary.Data;
global using PhoneDirectoryLibrary.Data.Interfaces;
global using Microsoft.AspNetCore.Components.Server.ProtectedBrowserStorage;
global using System.ComponentModel.DataAnnotations;
global using Microsoft.AspNetCore.Components;
global using Microsoft.AspNetCore.Components.Web;
global using PhoneDirectory;
